const sidebars = {
  // 各个产品独立的侧边栏
  opspilotSidebar: [{ type: 'autogenerated', dirName: 'opspilot' }],
  labSidebar: [{ type: 'autogenerated', dirName: 'lab' }],
  playgroundSidebar: [{ type: 'autogenerated', dirName: 'playground' }],
  monitorSidebar: [{ type: 'autogenerated', dirName: 'monitor' }],
  alertSidebar: [{ type: 'autogenerated', dirName: 'alert' }],
  logSidebar: [{ type: 'autogenerated', dirName: 'log' }],
  cmdbSidebar: [{ type: 'autogenerated', dirName: 'cmdb' }],
  nodeSidebar: [{ type: 'autogenerated', dirName: 'node' }],
  analysisSidebar: [{ type: 'autogenerated', dirName: 'analysis' }],
  mlopsSidebar: [{ type: 'autogenerated', dirName: 'mlops' }],
  consoleSidebar: [{ type: 'autogenerated', dirName: 'console' }],
  itsmSidebar: [{ type: 'autogenerated', dirName: 'itsm' }],
  systemSidebar: [{ type: 'autogenerated', dirName: 'system' }],

  // 其他文档侧边栏
  deploySidebar: [{ type: 'autogenerated', dirName: 'deploy' }],
  operationsSidebar: [{ type: 'autogenerated', dirName: 'operations' }],
  faqSidebar: [{ type: 'autogenerated', dirName: 'faq' }],
  assertsSidebar: [{ type: 'autogenerated', dirName: 'asserts' }],
  devSidebar: [{ type: 'autogenerated', dirName: 'dev' }],
};

export default sidebars;
